apiVersion: apps/v1
kind: Deployment
metadata:
  name: shopping-client-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: shopping-client
  template:
    metadata:
      labels:
        app: shopping-client
    spec:
      containers:
        - name: shopping-client
          image: crshopping.azurecr.io/shopping-client:v1
          imagePullPolicy: Always
          env:
            - name: ShoppingAPIUrl
              valueFrom:
                configMapKeyRef:
                  name: env
                  key: ShoppingAPIUrl
      imagePullSecrets:
        - name: acr-secret
---
apiVersion: v1
kind: Service
metadata:
  name: shopping-client-service
spec:
  selector:
    app: shopping-client
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 80
  type: LoadBalancer