services: 
  postgres-db:
    image: postgres:12.1-alpine
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres-data:/var/lib/postgresql/data
  adiminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
    depends_on:
      - postgres-db
  shopping.api:
    container_name: shopping.api
    image: shopping.api
    environment:
      ConnStr: host=postgres-db;database=shopping;username=postgres;password=postgres;
    build:
      context: .
      dockerfile: Shopping.API/Dockerfile
    ports:
      - 5001:80
    depends_on:
      - postgres-db
  shopping.client:
    container_name: shopping.client
    image: shopping.client
    build:
      context: .
      dockerfile: Shopping.Client/Dockerfile
    environment:
      - ShoppingAPIUrl=http://shopping.api
    depends_on: 
      - shopping.api
    ports:
      - 5000:80
volumes: 
  postgres-data: